### ISSUE TITLE
zpm image size

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/zpm-dockerhub#2]
Why does the ZPM image add 400 MB?

![image](https://user-images.githubusercontent.com/669176/99029241-a107bd00-2537-11eb-98ad-d022f3f78f84.png)

I am just getting up to speed with docker and am having trouble pinpointing why a simple library is taking up so much space. 

If you know the answer to this, perhaps you could also explain why the irishealth image is 2GB larger than the vanilla iris image?

![image](https://user-images.githubusercontent.com/669176/99029472-255a4000-2538-11eb-989a-14d6c366362f.png)

**Comment by daimor** [comment]
Yeah, it's a pain, but no way yet to solve, the issue is in how IRIS works and in docker images way.
The only way to solve it at the moment is to squash layers in the image, and in this case, instead of multiple layers, it will get one, and it's so good.

The issue in IRIS is, when you just start and stop IRIS during the build, it will do some changes in the system database, like some logs, or anything, it does not matter. This database is about 100MB, and Docker has to add any changed files entirely as a new layer. 

With this project, you can look, how the docker image looks inside, and what's changed the size
https://github.com/wagoodman/dive

![image](https://user-images.githubusercontent.com/1212251/99039269-1a36fc80-2598-11eb-8d40-3edfc7436bc2.png)

So, as you can see in the picture, any yellow files, are changed files, they increase the size of the layer. And the green ones are new. So, it would be possible to decrease a bit the size of the final image, with some cleanup.

**Comment by daimor** [comment]
I've removed some of the files, but it will grow for 100MB anyway. Mostly due to `/usr/irisys/mgr/IRIS.DAT`

**Comment by daimor** [comment]
> If you know the answer to this, perhaps you could also explain why the irishealth image is 2GB larger than the vanilla iris image?

You compare to vanilla images IRIS for Health and just IRIS, here is the difference in "for Health" part. It contains a few more databases and much some data
At least what I can find is, that HSLIB cost about 1.6GB

IRIS for Health
![image](https://user-images.githubusercontent.com/1212251/99068593-d951de80-25bd-11eb-83bc-c8dc703dd878.png)
And IRIS
![image](https://user-images.githubusercontent.com/1212251/99068634-ea9aeb00-25bd-11eb-8070-54cc0694088e.png)

**Comment by mvhenderson** [comment]
@daimor Thank you for the fix and pointing out this tool - very helpful.
